# Generated by Django 4.2.4 on 2023-09-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
